#!/usr/bin/env python3
"""Keep the CoAFarm addon's data current, on a timer.

Runs standalone: it downloads everything it needs, so no checkout of this
repository is required and the built exe can be handed to anyone.

Why it writes where it does -- a 3.3.5 addon cannot fetch anything itself, and
``SavedVariables`` is rewritten by WoW on logout, destroying outside edits. The
addon folder is only ever *read* by the game, so writing ``Data.lua`` there is
safe at any moment, including mid-session; ``/reload`` picks it up.

Two builds come out of this one script:

* ``CoAFarmSync.exe`` -- console. Run it and leave it open to watch each sync.
* ``CoAFarmSyncSilent.exe`` -- windowless. What the scheduled task runs, so
  nothing ever flashes up and steals focus. It writes to the log instead.

    CoAFarmSync.exe              # sync now, then every 15 minutes
    CoAFarmSyncSilent.exe --once # single run, no window, for Task Scheduler
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

PUBLISHED = "https://raw.githubusercontent.com/pbozic/coa-db/data/addon.json"
ADDON_NAME = "CoAFarm"
DEFAULT_INTERVAL = 900          # 15 minutes

# Where the Ascension launcher usually puts the client.
CLIENT_HINTS = [
    Path("C:/Games/Ascension/Launcher/resources/ascension-live"),
    Path("C:/Program Files/Ascension/Launcher/resources/ascension-live"),
    Path("C:/Program Files (x86)/Ascension/Launcher/resources/ascension-live"),
    Path.home() / "AppData/Local/Ascension/Launcher/resources/ascension-live",
]

LUA_FILES = ("CoAFarm.toc", "Core.lua", "Tooltip.lua", "UI.lua")


def bundled(name: str) -> Path | None:
    """Locate a file shipped inside the frozen exe, or beside the script."""
    root = Path(getattr(sys, "_MEIPASS", Path(__file__).parent))
    for candidate in (root / "addon" / ADDON_NAME / name, root / name):
        if candidate.exists():
            return candidate
    return None


def find_addons(explicit: Path | None = None) -> Path | None:
    if explicit:
        return explicit if explicit.exists() else None
    for base in CLIENT_HINTS:
        folder = base / "Interface" / "AddOns"
        if folder.exists():
            return folder
    return None


def say(message: str, log: Path | None) -> None:
    stamped = f"{dt.datetime.now():%Y-%m-%d %H:%M:%S}  {message}"
    # A windowed build has no stdout at all, so printing there would raise.
    if sys.stdout is not None:
        try:
            print(stamped, flush=True)
        except (OSError, ValueError):
            pass
    if log:
        try:
            log.parent.mkdir(parents=True, exist_ok=True)
            with log.open("a", encoding="utf-8") as handle:
                handle.write(stamped + "\n")
        except OSError:
            pass


def lua_string(value: str) -> str:
    escaped = (value.replace("\\", "\\\\").replace('"', '\\"')
               .replace("\n", "\\n").replace("\r", ""))
    return f'"{escaped}"'


def lua_value(value) -> str:
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(round(value, 2) if isinstance(value, float) else value)
    if isinstance(value, str):
        return lua_string(value)
    if isinstance(value, (list, tuple)):
        return "{" + ",".join(lua_value(v) for v in value) + "}"
    if isinstance(value, dict):
        parts = []
        for key, val in value.items():
            if val is None or val == [] or val == {}:
                continue
            # JSON turns integer keys into strings; Lua needs them back.
            slot = f"[{key}]" if isinstance(key, int) or str(key).isdigit() else key
            parts.append(f"{slot}={lua_value(val)}")
        return "{" + ",".join(parts) + "}"
    raise TypeError(f"cannot serialise {type(value)}")


def write_lua(payload: dict, path: Path) -> None:
    lines = [
        "-- Generated by CoAFarmSync. Do not edit by hand.",
        f"-- realm {payload.get('realm')}  scanned {payload.get('scanned')}",
        "",
        "CoAFarmData = {",
        f"  generated = {payload.get('generated', 0)},",
        f"  realm = {lua_value(payload.get('realm'))},",
        f"  scanned = {lua_value(payload.get('scanned'))},",
        f"  cut = {payload.get('cut', 0.05)},",
        "  items = {",
    ]
    for item_id, entry in sorted(payload["items"].items(), key=lambda kv: int(kv[0])):
        lines.append(f"    [{item_id}]={lua_value(entry)},")
    lines += ["  },", "  recipes = {"]
    for product, entry in sorted(payload["recipes"].items(), key=lambda kv: int(kv[0])):
        lines.append(f"    [{product}]={lua_value(entry)},")
    lines += ["  },", "}", ""]
    # Written whole, so the game never sees a half-finished file.
    temporary = path.with_suffix(".tmp")
    temporary.write_text("\n".join(lines), encoding="utf-8")
    os.replace(temporary, path)


def fetch(url: str) -> dict:
    request = urllib.request.Request(url, headers={"User-Agent": "CoAFarmSync"})
    with urllib.request.urlopen(request, timeout=45) as response:
        return json.loads(response.read().decode("utf-8"))


def sync(addons: Path, url: str, log: Path | None, install: bool) -> bool:
    try:
        payload = fetch(url)
    except (urllib.error.URLError, OSError, json.JSONDecodeError) as exc:
        say(f"download failed: {exc}", log)
        return False

    target = addons / ADDON_NAME
    target.mkdir(parents=True, exist_ok=True)

    if install:
        for name in LUA_FILES:
            source = bundled(name)
            if source:
                (target / name).write_bytes(source.read_bytes())
        say(f"addon files installed into {target}", log)

    data_file = target / "Data.lua"
    previous = data_file.stat().st_mtime if data_file.exists() else 0
    write_lua(payload, data_file)

    say(f"{len(payload['items'])} items, {len(payload['recipes'])} recipes"
        f" - prices from {payload.get('scanned', '?')}"
        f" - {'updated' if previous else 'created'} {data_file.name}", log)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--once", action="store_true", help="sync once and exit")
    parser.add_argument("--interval", type=float, default=DEFAULT_INTERVAL,
                        help="seconds between syncs (default 900)")
    parser.add_argument("--addons", type=Path, help="Interface/AddOns folder")
    parser.add_argument("--url", default=PUBLISHED)
    parser.add_argument("--install", action="store_true",
                        help="also write the addon's Lua files, not just the data")
    parser.add_argument("--log", type=Path, help="append activity to this file")
    args = parser.parse_args()

    addons = find_addons(args.addons)
    if not addons:
        say("Could not find the Ascension client. Pass --addons "
            r'"...\Interface\AddOns".', args.log)
        if not args.once and sys.stdin is not None:
            try:
                input("Press Enter to close.")
            except (OSError, ValueError):
                pass
        return 1

    say(f"CoA Farm sync - {addons}", args.log)
    # First run lays the addon down if it is not there yet.
    install = args.install or not (addons / ADDON_NAME / "Core.lua").exists()

    if args.once:
        return 0 if sync(addons, args.url, args.log, install) else 1

    say(f"syncing every {args.interval / 60:.0f} minutes. Ctrl+C to stop. "
        f"Use /reload in game to pick up new prices.", args.log)
    try:
        while True:
            sync(addons, args.url, args.log, install)
            install = False
            time.sleep(args.interval)
    except KeyboardInterrupt:
        say("stopped", args.log)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
